require "rake/clean"

TARGET = "starruby-launcher"
if (exeext = Config::CONFIG["EXEEXT"]) and not exeext.empty?
  TARGET << "#{exeext}"
end

INCFLAGS = "-I."

if Config::CONFIG['arch'] =~ /mingw/
  CFLAGS = `env wx-config --cppflags`.chomp.gsub("/usr/local", "C:/msys/1.0/local")
else
  CFLAGS = `wx-config --cppflags`.chomp
end
CFLAGS << " -fno-strict-aliasing -Wall -mfpmath=sse -msse2 -funit-at-a-time -O3"

DLDFLAGS = "-Wl,-export-dynamic -L. -L/usr/lib"

if Config::CONFIG['arch'] =~ /mingw/
  LIBS = `env wx-config --libs`.chomp.gsub("/usr/local", "C:/msys/1.0/local")
else
  LIBS = `wx-config --libs`.chomp
end

SRCS = FileList["**/*.cpp"]
OBJS = SRCS.ext("o")
CLEAN.include(OBJS)
CLOBBER.include(TARGET)

task :default => TARGET

task TARGET => OBJS do |t|
  sh "g++ -o #{t.name} #{t.prerequisites.join(' ')} #{DLDFLAGS} #{LIBS} "
end

rule ".o" => ".cpp" do |t|
  sh "g++ -c #{t.source} #{INCFLAGS} #{CFLAGS}"
end
