require "rake/clean"

TARGET = "ruby"
if (exeext = Config::CONFIG["EXEEXT"]) and not exeext.empty?
  TARGET << "#{exeext}"
end

INCFLAGS = "-I. -I#{Config::CONFIG['archdir']}"

if Config::CONFIG['arch'] =~ /mingw/
  CFLAGS = `env sdl-config --cflags`.chomp.gsub("/usr/local", "C:/msys/1.0/local")
else
  CFLAGS = `sdl-config --cflags`.chomp + " -fPIC"
end
CFLAGS << " -fno-strict-aliasing -Wall -mfpmath=sse -msse2 -funit-at-a-time -O3"

DLDFLAGS = "-L. -L/usr/lib #{Config::CONFIG['LIBRUBYARG']}"

if Config::CONFIG['arch'] =~ /mingw/
  LIBS = `env sdl-config --libs`.chomp.gsub("/usr/local", "C:/msys/1.0/local")
else
  LIBS = `sdl-config --libs`.chomp
end

SRCS = FileList["./*.c"]
OBJS = SRCS.ext("o")
CLEAN.include(OBJS)
CLOBBER.include(TARGET)

task :default => TARGET

task TARGET => OBJS do |t|
  sh "gcc -o #{t.name} #{t.prerequisites.join(' ')} #{DLDFLAGS} #{LIBS} "
end

rule ".o" => ".c" do |t|
  sh "gcc -c #{t.source} #{INCFLAGS} #{CFLAGS}"
end
